# Generated by Django 6.0.1 on 2026-01-29 18:41

import cv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_alter_datospersonales_licenciaconducir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosacademicos',
            name='archivo_digital',
            field=models.FileField(blank=True, null=True, upload_to=cv.models.upload_prod_acad, verbose_name='Subir PDF/Imagen'),
        ),
        migrations.AddField(
            model_name='productosacademicos',
            name='rutacertificado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Link Externo'),
        ),
        migrations.AddField(
            model_name='productoslaborales',
            name='archivo_digital',
            field=models.FileField(blank=True, null=True, upload_to=cv.models.upload_prod_lab, verbose_name='Subir PDF/Imagen'),
        ),
        migrations.AddField(
            model_name='productoslaborales',
            name='rutacertificado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Link Externo'),
        ),
    ]
